services:
  db:
    image: mysql:oraclelinux9
    container_name: note_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - data:/var/lib/mysql
    networks:
      - note_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8888:8080"
    networks:
      - note_net
    depends_on:
      - db
    restart: always

  note_app:
    build: ./backend
    container_name: note_app
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      DB_URL: note_db:3306
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - note_net
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  note_frontend:
    build: ./frontend
    container_name: note_frontend
    ports:
      - "3000:80"
    networks:
      - note_net
    depends_on:
      - note_app
    restart: unless-stopped

volumes:
  data:

networks:
  note_net:
    driver: bridge
