services:
  db:
    image: mysql:oraclelinux9
    container_name: note_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

# Manejo de db
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
#  task_list_app:
#    build: .
#    container_name: note_app
#    ports:
#      - "8080:8080"
#    environment:
#      DB_URL: note_db:3306
#      DB_USERNAME: ${DB_USERNAME}
#      DB_PASSWORD: ${DB_PASSWORD}
#      JWT_SECRET: ${JWT_SECRET}
#      SPRING_PROFILES_ACTIVE: prod
#    depends_on:
#      note_db:
#        condition: service_healthy
#    restart: unless-stopped

volumes:
  data:
