services:
  task_list_db:
    image: mysql:oraclelinux9
    container_name: task_list_db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my_secret
      MYSQL_DATABASE: task_list
    volumes:
      - task_list_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  task_list_data:
